### ISSUE TITLE
Package Control does not exist, link to instructions is broken.

### ISSUE THREAD

**Issue by grantpowell** [SublimeText/ColdFusion#158]
As usual, anything that is open source is generally completely useless and I am better off building something myself from scratch.

WTF is "Package Control"? It does not exist in Sublime Text 3.

Dead link for instructions: http://wbond.net/sublime_packages/package_control

**Comment by jimpriest** [comment]
There is an "Instructions" link on the Package Control home page which points to:
https://packagecontrol.io/installation

Make sure you install the correct version (2/3) for your version of Sublime.

And let us know when you write your own editor.

**Comment by DominicWatson** [comment]
> WTF is "Package Control"?

http://lmgtfy.com/?q=Package control

Can't wait to see what you produce.

**Comment by Demasso** [comment]
https://packagecontrol.io/installation
Package control and all that github thing is a bit awkward at first, but once you get the hang of it you' won't be able to live without it !

**Comment by atuttle** [comment]
And [what a prolific creator you are, Grant](https://github.com/grantpowell?tab=repositories). Maybe next time just say something like this in your ticket: "The readme mentions something called Package Control but I can't find it in my ST3 install and I'm new to Sublime... What am I missing?"

You know, rather than insulting everyone that works on the free open source software that you take for granted because you were too lazy to google.

**Comment by grantpowell** [comment]
Developers are all ego and no value. Just because something hypothetically could be great if it worked is completely meaningless.  I don't care if this software could navigate a spaceship to the moon - if I can't install it, then it is useless. I spent 30 minutes googling, reading and having failed attempts at installing before giving up.

Open source development is an intrinsically flawed concept and leads to these such outcomes.

Point in case, the link in your comment above is to a branch of another open source project which I attempted to use and was a total failure.  I did in fact, build a Facebook OAuth library from scratch, in one day, and it is working gloriously. Keep in mind, I don't consider myself a good developer - so how is it that I can build such things when the real good developers cannot?

Sorry guys, I don't mean to be a dick, but it's this mentality that developers have which has lost me millions of dollars. It's time for a shift in the way developers think and work.

**Comment by jimpriest** [comment]
It's time for a shift in the way you ask for help.  But lets stop pointing fingers :)

Did you get it installed?  Can you follow these instructions: https://packagecontrol.io/installation

It doesn't get any simpler than that. Cut n paste a string, open Sublime's console. Paste. Done.

**Comment by bbluemel** [comment]
Jim, I would say give up, he's obviously not interested in getting it working, and just using this as a venting platform.
He's obviously used git, but seemingly can't even follow the install instructions for cloning the repo into the packages directory. (which is what he should be doing given that he said he's using SublimeText 3 and the first main line of the readme under SublimeText 3 is::
> The development branch contains a rewrite of the ColdFusion plugin. The only installation method is via Git.

)
Grant, if you're serious about getting it running, raise a new issue and rather than spend your precious minutes complaining and giving a sob story about how developers have "lost you millions", actually give us information about your set up, and what you have tried.

Closing and locking.

**Comment by atuttle** [comment]
> As usual, anything that is open source is generally completely useless and I am better off building something myself from scratch.

So I linked your own github profile. 

> Point in case, the link in your comment above is to a branch of another open source project which I attempted to use and was a total failure. I did in fact, build a Facebook OAuth library from scratch, in one day, and it is working gloriously.

You've got no evidence you've built anything from scratch, at least not to boast about in a public forum.

---

Now, you say you spent 30 minutes googling. I find this claim dubious. Literally the first result for ["package control"](https://www.google.com/search?q=package+control&oq=package+control&aqs=chrome..69i57j69i60j69i61.1833j0j7&sourceid=chrome&es_sm=91&ie=UTF-8) is the correct website, and it even has a surfaced link for **Installation** right in the google results.

If you couldn't figure out how to install Package Control, that's on you. The process is about as simple as it could possibly get, and the directions are clear and easy to find.

To add insult to injury, you came in here claiming that the plugin/documentation (and by extension, the developers that have built it for you) are "completely useless." Had you simply been nice, none of this discussion would have happened. Look through the closed issues on this repository, there are dozens of people that needed help getting it installed and they were all met with kind, generous, and rapid help, because they weren't assholes.

Part of me wants to just ignore this thread / you, because you haven't shown that you are worth my time. BUT that's not what open source is about, so in the spirit of the project, here you go, literally everything you need to do to get Package Control installed:

1. Keyboard shortcut <code>ctrl+`</code>, or if you prefer menus, **View > Show Console**
1. Then copy this string to your clipboard: `import urllib.request,os,hashlib; h = 'eb2297e1a458f27d836c04bb0cbaf282' + 'd0e7a3098092775ccb37ca9d6b2e4b7d'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)`
1. Paste it into the console and hit the return key. Wait a few moments while PC is downloaded and installed. You will probably need to restart for it to take effect.
1. Now, when you have some time (when you're not busy creating loads of great software that us useless open source contributors couldn't possibly get right), read up a little bit on [the great features that Package Control has to offer](https://packagecontrol.io/docs/usage). It's pretty awesome, and you'll probably like it a lot. I only linked the end-user docs. On the off chance that you want to _create_ a package, or do other more advanced things, there is [more documentation available here](https://packagecontrol.io/docs).

### Now some bad news:

Had you actually bothered to read the readme, you would know that you can't install this plugin in ST3 using package control. Instead, you'll need to install via git. 

> The development branch contains a rewrite of the ColdFusion plugin. The only installation method is via Git.

You can either:

- [download this zip](https://github.com/SublimeText/ColdFusion/archive/development.zip), and unpack it into [your packages folder](http://docs.sublimetext.info/en/latest/basic_concepts.html#the-packages-directory) ("Preferences > Browse Packages..." to find it) so that you have **Packages/ColdFusion/** NOT **Packages/User/ColdFusion/**
- or open your packages folder in a terminal window and install it with this one-liner: `git clone https://github.com/SublimeText/ColdFusion.git && cd ColdFusion && git checkout development` (Assumes you're on Linux or Mac, since your bug report didn't bother to specify.)

After either, you should restart Sublime for the changes to take effect.

Have a nice day!
